CREATE TABLE IF NOT EXISTS `PACIENTES` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`lastname` VARCHAR(255) NOT NULL,
	`cedula` VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `MEDICOS` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`lastname` VARCHAR(255) NOT NULL,
	`especialidad` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `CITAS` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`id_paciente` INTEGER NOT NULL,
	`id_medico` INTEGER NOT NULL,
	`id_diagnostico` INTEGER NOT NULL,
	`date` DATE NOT NULL,
	`hour` DATETIME NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `DIAGNOSTICOS` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`type` VARCHAR(255) NOT NULL,
	`description` TEXT(65535) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `CITAS_DIAGNOSTICOS` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`id_citas` INTEGER NOT NULL,
	`id_diagnostico` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


ALTER TABLE `CITAS`
ADD FOREIGN KEY(`id_medico`) REFERENCES `MEDICOS`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CITAS`
ADD FOREIGN KEY(`id_paciente`) REFERENCES `PACIENTES`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CITAS_DIAGNOSTICOS`
ADD FOREIGN KEY(`id_citas`) REFERENCES `CITAS`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CITAS_DIAGNOSTICOS`
ADD FOREIGN KEY(`id_diagnostico`) REFERENCES `DIAGNOSTICOS`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;